defaults:
  - judo_dora_default

task: leap_freejoint_object_pick
optimizer: cem
custom_tasks:
  leap_freejoint_object_pick:
    task: judo.tasks.leap_freejoint_object_pick.LeapFreeJointObjectPick
    config: judo.tasks.leap_freejoint_object_pick.LeapFreeJointObjectPickConfig

custom_optimizers:
  cem:
    optimizer: judo.optimizers.cem.CrossEntropyMethod
    config: judo.optimizers.cem.CrossEntropyMethodConfig

# example of how to use task-specific controller config overrides
controller_config_overrides:
  leap_freejoint_object_pick:
    horizon: 1.0
    spline_order: ZERO

optimizer_config_overrides:
  leap_freejoint_object_pick:
    cem:
      num_rollouts: 128

simulation_backend: MUJOCO
