defaults:
  - judo_dora_default

task: leap_cube_down
optimizer: cem
custom_tasks:
  leap_cube_down_rotate:
    task: judo.tasks.leap_cube_down.LeapCubeDown
    config: judo.tasks.leap_cube_down.LeapCubeDownConfig

custom_optimizers:
  cem:
    optimizer: judo.optimizers.cem.CrossEntropyMethod
    config: judo.optimizers.cem.CrossEntropyMethodConfig

# example of how to use task-specific controller config overrides
controller_config_overrides:
  leap_cube_down:
    horizon: 1.0
    spline_order: ZERO

optimizer_config_overrides:
  leap_cube_down:
    cem:
      num_rollouts: 128

simulation_backend: MUJOCO
