defaults:
  - judo_dora_default

task: triple_pandas_rotate
optimizer: cem
custom_tasks:
  triple_pandas_rotate:
    task: judo.tasks.triple_pandas_rotate.TriplePandasRotate
    config: judo.tasks.triple_pandas_rotate.TriplePandasRotate

custom_optimizers:
  cem:
    optimizer: judo.optimizers.cem.CrossEntropyMethod
    config: judo.optimizers.cem.CrossEntropyMethodConfig
    #mppi:
    #optimizer: judo.optimizers.mppi.MPPI
    #config: judo.optimizers.mppi.MPPIConfig

# example of how to use task-specific controller config overrides
controller_config_overrides:
  triple_pandas_rotate:
    horizon: 0.25
    spline_order: ZERO

optimizer_config_overrides:
  triple_pandas_rotate:
    ps:
      num_nodes: 4
      num_rollouts: 128
      use_noise_ramp: true
      noise_ramp: 4.0
      sigma: 0.2

simulation_backend: MUJOCO
