defaults:
  - judo_dora_default

task: allegro_cube
optimizer: cem
custom_tasks:
  iiwa7_allegro_pick:
    task: judo.examples.iiwa7_allegro_pick.IIWA7AllegroPick
    config: judo.examples.iiwa7_allegro_pick.IIWA7AllegroPickConfig

custom_optimizers:
  cem:
    optimizer: judo.optimizers.cem.CrossEntropyMethod
    config: judo.optimizers.cem.CrossEntropyMethodConfig

# example of how to use task-specific controller config overrides
controller_config_overrides:
  iiwa7_allegro_pick:
    horizon: 0.25
    spline_order: ZERO

optimizer_config_overrides:
  iiwa7_allegro_pick:
    ps:
      num_nodes: 4
      num_rollouts: 128
      use_noise_ramp: true
      noise_ramp: 4.0
      sigma: 0.2

simulation_backend: MUJOCO
